name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd docker/ && docker build . --file Dockerfile --tag static-php
    - name: Push binary into new branch
      run: |
        mkdir dist && docker run --rm -v $(pwd)/dist:/dist/ static-php cp php-dist/bin/php /dist/
        chmod a+x action-deploy.sh
        ./action-deploy.sh
